# SPDX-License-Identifier: GPL-3.0-only
# Exercise the built executable using only disposable synthetic session data.
cmake_minimum_required(VERSION 3.28)
foreach(required SESSION_DOCTOR SOURCE_DIR TEST_ROOT)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${TEST_ROOT}-${suffix}")
if(EXISTS "${root}")
  message(FATAL_ERROR "Refusing existing fixture directory: ${root}")
endif()
file(MAKE_DIRECTORY "${root}")

function(run_doctor path expected_exit expected_output)
  execute_process(COMMAND "${SESSION_DOCTOR}" "${path}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT "${result}" STREQUAL "${expected_exit}" OR
     NOT "${output}${error}" MATCHES "${expected_output}")
    message(FATAL_ERROR
      "session_doctor ${path}: exit=${result}; stdout=${output}; stderr=${error}")
  endif()
endfunction()

run_doctor("--help" 0 "Usage: session_doctor")
run_doctor("${root}/missing.mmsession" 2 "recovery failed:")

# A finalized repository fixture must remain byte-identical.
set(finalized "${root}/finalized.mmsession")
file(COPY "${SOURCE_DIR}/tests/fixtures/mini_session/" DESTINATION "${finalized}")
file(SHA256 "${finalized}/manifest.json" manifest_before)
file(GLOB_RECURSE raw_files "${finalized}/sources/*.mcap")
set(raw_before)
foreach(raw IN LISTS raw_files)
  file(SHA256 "${raw}" hash)
  list(APPEND raw_before "${hash}")
endforeach()
run_doctor("${finalized}" 0 "state=finalized recovered=false")
file(SHA256 "${finalized}/manifest.json" manifest_after)
set(raw_after)
foreach(raw IN LISTS raw_files)
  file(SHA256 "${raw}" hash)
  list(APPEND raw_after "${hash}")
endforeach()
if(NOT manifest_before STREQUAL manifest_after OR NOT raw_before STREQUAL raw_after)
  message(FATAL_ERROR "Finalized fixture bytes changed")
endif()

# A valid MCAP magic followed by an incomplete record header exercises the
# platform truncation seam. This deliberately contains no captured samples.
set(recording "${root}/synthetic-tail.mmsession")
set(segment "${recording}/sources/sim.portable/streams/sim.portable.numeric/segments/000000.mcap")
get_filename_component(segment_parent "${segment}" DIRECTORY)
file(MAKE_DIRECTORY "${segment_parent}")
file(WRITE "${recording}/manifest.json"
  "{\"sessionSchemaVersion\":\"1.0.0\",\"sessionId\":\"synthetic-portable-tail\",\"state\":\"recording\"}\n")
string(ASCII 137 77 67 65 80 48 13 10 magic)
string(ASCII 6 incomplete_record)
file(WRITE "${segment}" "${magic}${incomplete_record}")
run_doctor("${recording}" 0 "state=finalized_recovered recovered=true")
file(SIZE "${segment}" remaining_bytes)
if(NOT remaining_bytes EQUAL 8)
  message(FATAL_ERROR "Incomplete header was not truncated to MCAP magic")
endif()
file(READ "${recording}/manifest.json" manifest)
string(JSON state GET "${manifest}" state)
if(NOT state STREQUAL "finalized_recovered")
  message(FATAL_ERROR "Recovery did not persist its state")
endif()
file(GLOB reports "${recording}/recovery/report_*.json")
list(LENGTH reports report_count)
if(NOT report_count EQUAL 1)
  message(FATAL_ERROR "Recovery must retain one report")
endif()
list(GET reports 0 report_path)
file(READ "${report_path}" report)
string(JSON truncated_count LENGTH "${report}" truncated)
if(NOT truncated_count EQUAL 1)
  message(FATAL_ERROR "Truncation was not reported explicitly")
endif()
file(SHA256 "${recording}/manifest.json" recovered_before)
run_doctor("${recording}" 0 "state=finalized_recovered recovered=false")
file(SHA256 "${recording}/manifest.json" recovered_after)
if(NOT recovered_before STREQUAL recovered_after)
  message(FATAL_ERROR "Second recovery invocation changed finalized metadata")
endif()
file(REMOVE_RECURSE "${root}")
message(STATUS "session_doctor portable fixture checks passed")
