# SPDX-License-Identifier: GPL-3.0-only
# Protobuf generation for C++ (populated when vcpkg toolchain is active).
# Python bindings are generated by tools/gen_protos.py and committed.

find_package(Protobuf CONFIG QUIET)
if(NOT Protobuf_FOUND)
  find_package(protobuf CONFIG QUIET)
endif()
if(NOT Protobuf_FOUND)
  find_package(Protobuf QUIET)
endif()

if(Protobuf_FOUND OR protobuf_FOUND)
  if(DEFINED Protobuf_VERSION)
    message(STATUS "Protobuf ${Protobuf_VERSION} found — C++ codegen enabled")
  else()
    message(STATUS "Protobuf found — C++ codegen enabled")
  endif()
  set(CAPTURE_PROTOBUF_FOUND TRUE)
else()
  message(STATUS "Protobuf not found — C++ codegen deferred (Python bindings still available)")
  set(CAPTURE_PROTOBUF_FOUND FALSE)
endif()
